### ISSUE TITLE
difference counts in regression diff report are wrong

### ISSUE THREAD

**Issue by Vampire** [checkstyle/contribution#362] opened 2019-03-22 15:02 UTC
The difference values of the diff report are wrong:
![grafik](https://user-images.githubusercontent.com/325196/54832125-dead3780-4cbb-11e9-87e6-abcc5c8d2780.png)
When fixing this, it could also be evaluated to also show the difference with `+` and `-` prefix.

**Comment by rnveach** [comment] 2019-03-22 15:24
Please link us to the report and say what is wrong and why you think it is wrong.

**Comment by Vampire** [comment] 2019-03-22 15:47
This example is from http://kautler.net/cs-regression-6466/ and I said what I think is wrong. 39-39!=35 and 1050-336!=730. If the values are correct it is at best unclear what they mean. How they are presented make me think it should be the difference

**Comment by rnveach** [comment] 2019-03-22 16:46
> This example is from http://kautler.net/cs-regression-6466/

You gave the splash page report and not the specific report with the counts.
Going by the counts it looks to be this one: http://kautler.net/cs-regression-6466/android-launcher/index.html

> 1050-336!=730

These counts don't represent the sum of the differences, but show the overall number of different violations. If a project had a violation added and a violation removed, you wouldn't expect the differences to display 0. Saying the report has 0 differences would make someone incorrectly assume there were no differences at all and would think it is ok to ignore the report. In this scenario, the utility should display 2 as the number of differences as that is how many different violations it found.

> 39-39!=35 

Same here. This shows the overall number of files that had differences for violations in them. You wouldn't expect 0 to be displayed here because then that is it's own confusion like "Where did the violations come from if 0 files had differences".

> http://kautler.net/cs-regression-6466/android-launcher/index.html
1050
336
730
Number of unique base messages reported below: 722
Number of unique patch messages reported below: 8

722 + 8 = 730
1050 - 722 + 8 = 336

http://kautler.net/cs-regression-6466/android-launcher/index.html#A730 is the last violation in the file and it's link says it is number 730 (links start at 1).

Doing a search on `D:\Sourcecode\other` shows that there is 35 files being displayed in the report that contain differences. (I thought we also had links on the files too?)

The counts appear to be correct.

**Comment by rnveach** [comment] 2019-03-22 16:54
If the confusion is in the word "difference", I am fine with changing it if we can agree on the right verbage.

**Comment by romani** [comment] 2019-03-23 01:56
@Vampire , please propose update to words or is there some embedded note should be present, to make it more clear for new users.

**Comment by Vampire** [comment] 2019-03-25 04:01
Ahhh, with this information it makes much more sense.
Yes, this logic makes sense of course.
But yes, I think a different word than `difference` or a different visual representation would be better for intuitiveness.
Like it is presented right now can easily give the impression that the thrid line is the difference between the first two ones.
Maybe `difference` is ok if the cell representation changes.
For example in the `Files` column `xx files with differences` and in the other columns two lines, first line `-xx` second line `+xx` to make it more visible what it means and to also see the numbers individually.

**Comment by rnveach** [comment] 2019-03-25 15:02
> in the `Files` column `xx files with differences`

This sounds fine to me. I would think we would have to remove the label `difference` completely.

> in the other columns two lines, first line -xx second line +xx 

I am not sure about this. Instead of displaying 1 number you want to display 3 with the only differences between all 3 is a `+` and a `-`. I see this adding more confusion then less.
![summary1](https://user-images.githubusercontent.com/5427943/54929891-a6d90680-4eec-11e9-8747-e59eb49a00a8.png)
(if my representation is wrong please provide a visual to clarify).

How about the following instead?
![summary2](https://user-images.githubusercontent.com/5427943/54930186-367eb500-4eed-11e9-9b67-5026a7f32ff9.png)

I do think there is too many words here. I was going to just do numbers only for the 2nd row (`336 (722 removed, 8 added)`), but I don't know if the point was going to get across clearly.
I would prefer to just reword `difference` on the side, but I am not sure of a good word that would describe this situation.

**Comment by Vampire** [comment] 2019-03-26 03:52
Why do you think I meant three lines when I said two lines?
Not two additional lines, just two lines, like

![grafik](https://user-images.githubusercontent.com/325196/54970354-1816c900-4f82-11e9-83ef-86ae528cfb86.png)

Or maybe something like

![grafik](https://user-images.githubusercontent.com/325196/54970541-c7ec3680-4f82-11e9-86e0-943eeb51906c.png)

Or what you suggested secondly.

Even if we find a better word for "difference", the separate numbers might still be more interesting than the total number, which I don't think is absolutely necessary as all as you see in my first suggestion.

**Comment by romani** [comment] 2019-03-26 05:44
I am against "fixed new" variant. Diff doesn't know what is good or bad, fixed or regression , ... .

**Comment by rnveach** [comment] 2019-03-26 10:51
> Why do you think I meant three lines when I said two lines?

I guess I just assumed you would want to keep the overall total since you didnt mention removing it. We would have to keep it somewhere since that is what the splash page uses as a count for that specific report.

> the separate numbers might still be more interesting than the total number

Do we need them in the table? Like I pasted above, they are actually shown outside the table in text form.

> Number of unique base messages reported below: 722
Number of unique patch messages reported below: 8

> I am against "fixed new" variant

Agree.

**Comment by Vampire** [comment] 2019-03-26 17:39
> I am against "fixed new" variant. Diff doesn't know what is good or bad, fixed or regression , ... .

Good point, was just brain-storming :-)

> > the separate numbers might still be more interesting than the total number
> 
> Do we need them in the table? Like I pasted above, they are actually shown outside the table in text form.
> 
> > Number of unique base messages reported below: 722
> > Number of unique patch messages reported below: 8

I think we do, because there is only one such count outside the table, so the count for the "Violations" column, but the counts for the other columns are probably different.

Also having only the total in the table still for my feeling is too unintuitive, but you can of course also overrule me and ignore my confusion, now that I know what the numbers mean. :-)

Maybe with the removed and added in parentheses in the patch line it is obvious enough to think about it.

> We would have to keep it somewhere since that is what the splash page uses as a count for that specific report.

We could also move the individual numbers into the table and have the sum outside the table, because the number on the splash page is not related to any column visually.

**Comment by romani** [comment] 2019-03-27 02:23
I am ok with first proposed variant , if @rnveach ok, let's move forward.

**Comment by Vampire** [comment] 2019-03-30 01:50
@romani can you clarify which one exactly you are ok with?
My first suggestion with the `-`-count and `+`-count in the line?
The one with three numbers in the line?
...?

**Comment by romani** [comment] 2019-03-30 12:31
first picture, with `35 files with difference`

**Comment by rnveach** [comment] 2019-03-30 13:51
I believe he is referring to 
https://user-images.githubusercontent.com/5427943/54930186-367eb500-4eed-11e9-9b67-5026a7f32ff9.png

**Comment by romani** [comment] 2019-03-30 13:52
yes, this is what I tried to rerfrence too.

**Comment by rnveach** [comment] 2019-03-30 13:58
I am ok with this.
Summary report is used to create front page report, so logic in parsing summary will need to change slightly. In this example 730 in difference row violations column is pulled and placed on front page for the project.

**Comment by Vampire** [comment] 2019-04-07 23:33
Which do you like more?

![grafik](https://user-images.githubusercontent.com/325196/55691359-dd5b5a80-599d-11e9-8e84-574fc3d0586a.png)

or

![grafik](https://user-images.githubusercontent.com/325196/55691409-3b883d80-599e-11e9-8a1c-de8080fe716a.png)

**Comment by rnveach** [comment] 2019-04-08 00:03
I am fine with dropping the wording for added/removed if the number is going to be 0.

**Comment by Vampire** [comment] 2019-04-08 02:02
Yes, that's the difference I mean, sorry, thought it is obvious, but there could of course be other differences smuggled in. :-D

**Comment by romani** [comment] 2019-09-09 04:21
fix is merged

**Closed by romani** 2019-09-09 04:21 UTC
