### ISSUE TITLE
local repos in checkstyle-tester

### ISSUE THREAD

**Issue by Vampire** [checkstyle/contribution#355] opened 2019-03-16 19:09 UTC
The documentation of checkstyle-tester suggests it once supported local paths for repos.
While this is still possible when it is a local Git or Hg repository (example gets fixed in #354), it would be nice to support a "local" type to support any VCS including none, local repositories with modified working trees and it would also save the space in `repositories`.

Actually what I suppose ist just this which I could PR if you like it:

```diff
-                cloneRepository(repoName, repoType, repoUrl, commitId, reposDir)
                 deleteDir(srcDir)
-                copyDir(getOsSpecificPath("$reposDir", "$repoName"), getOsSpecificPath("$srcDir", "$repoName"))
+                if (repoType == 'local') {
+                    copyDir(repoUrl, getOsSpecificPath("$srcDir", "$repoName"))
+                } else {
+                    cloneRepository(repoName, repoType, repoUrl, commitId, reposDir)
+                    copyDir(getOsSpecificPath("$reposDir", "$repoName"), getOsSpecificPath("$srcDir", "$repoName"))
+                }
```

**Comment by Vampire** [comment] 2019-03-16 19:12
Actually with this you could even check the current state of all local projects you have available if you have enough space on your disk to copy them to `src/main/java` and have them all under one common root with something like `all-local-projects|local|d:/Sourcecode/|||` if all your projects live in `d:/Sourcecode/`.

**Comment by romani** [comment] 2019-03-17 05:44
I am ok with this

**Comment by rnveach** [comment] 2019-03-17 14:06
> Actually with this you could even check the current state of all local projects you have available 

I don't recommend this as some projects create a lot of violations. With too many differences in 1 report, it will be very hard to open the report in a browser or scan it for unique cases.
I have also run into an issue with the diff-report-tool and it ran out of memory on a 256 gig file.

**Comment by rnveach** [comment] 2019-03-17 18:06
Fix merged, just waiting on documentation.

**Comment by romani** [comment] 2019-03-17 18:07
@rnveach , are you ok with such update or not ?

**Comment by rnveach** [comment] 2019-03-17 18:09
@romani yes I am ok with it as I merged it. :)
I just don't recommend putting many projects into 1 folder.
If you want to run regression against your own local/private repos, I am no problems.

**Comment by rnveach** [comment] 2019-03-17 18:11
I was leaving the issue open, since we still have to update documentation to show how to use such option since we added other examples in previous PR.

**Comment by romani** [comment] 2019-03-17 18:19
@Vampire, please provide update to readme.

**Closed** 2019-03-18 13:42 UTC
