### ISSUE TITLE
diff reports: need to have WARNING in HTML report or ....

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#199] opened 2017-03-16 00:57 UTC
ignorance of exclusions were added at #155
but caused confusion at https://github.com/checkstyle/checkstyle/pull/3928

that cost me a while to understand why this happening.
in case of PR having excludes ignored - was inconvenience.

**Comment by romani** [comment] 2017-03-16 00:57
@MEZk , @rnveach , please share your ideas.

**Comment by rnveach** [comment] 2017-03-16 02:59
@romani The whole point of diff reports is to see regression in Java code against changes in our checks, not to predict what violations will be like in our project by enabling new stuff.

IMO, it shouldn't matter where the file comes from. If it is a java file and it is compilable, we should scan it for regression purposes. Just like we want regression on multiple projects, we should have regression on all possible files as you never know where you will get an interesting result.

I still stand by this option being enabled by default. It can be disabled by CLI.
This is almost the same reason why we turn off `failsOnError` for regression too.

>  it looks like we have problems in Checkstyle project. Package name is not the same as directory for the following classes: InputAstTreeStringPrinterComments, InputAstTreeStringPrinterJavadoc, InputDeclarationOrderAvoidDuplicatesInStaticFinalFields and other.

I wanted to add support to fix this in https://github.com/checkstyle/checkstyle/issues/3072 . Eclipse use to notify me of these issues until I disabled compiling test resources. This is why for the `Split and Organize` issues, I ask people to change package and class name.

------

In terms of this issue and to make it clearer, how about we add `excludes` to each project's HTML report? No excludes should say `None` in bold and red.
This will require an extra argument to `patch-diff-report-tool` that groovy will have to pass.

**Comment by MEZk** [comment] 2017-03-19 16:17
@rnveach 
> Just like we want regression on multiple projects, we should have regression on all possible files as you never know where you will get an interesting result.

Agree. It is a one of the ways to find NPE in the code, because usually, the code in excludes i so ugly and unpredictable.

> In terms of this issue and to make it clearer, how about we add excludes to each project's HTML report? No excludes should say None in bold and red.

Thus, you suggest adding the new column in a diff report or a separate section? I think the separate section will be a good idea.

> This will require an extra argument to patch-diff-report-tool that groovy will have to pass.
Please, explain what do you mean. How do you want to collect the information about excludes from Checkstyle reports?

**Comment by rnveach** [comment] 2017-03-19 17:53
@MEZk 
> new column in a diff report or a separate section? 

I was originally thinking directly in the diff report as each project could have a separate excludes and user could disable ignoring excludes, but now I see we don't allow user to disable it in `diff.groovy`. It is only configurable for `launch.groovy` and it doesn't generate diff reports. My bad for the confusion.

I guess we should only put this as a warning on `diff.groovy`'s main index at https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L251 .

**Comment by romani** [comment] 2017-03-22 18:11
> No excludes should say None in bold and red.
This will require an extra argument to patch-diff-report-tool that groovy will have to pass.

I ok to skip excludes in diff reports.
But that is very hidden nuance, that I just want to move as Note/Warning to reports generation.
Because tool is following config ....... but it ignores part of it (excludes) silently ...... not very good.
It could be an parameter `patch-diff-report-tool ........... -warning "Excludes are ignored ......."` and it will placed in certain place in template.

Are you ok with this ?

**Comment by rnveach** [comment] 2017-03-22 18:16
> It could be an parameter patch-diff-report-tool ........... -warning "Excludes are ignored ......." 
> Are you ok with this ?

@romani 
I am fine with it.
Are you sure you don't want the notification on groovy's main index instead? It is the one controlling the excludes.

**Comment by romani** [comment] 2017-03-22 18:51
>groovy's main index 

What is it ? Please point to a line in code

**Comment by rnveach** [comment] 2017-03-22 18:54
> What is it ? Please point to a line in code

https://github.com/checkstyle/contribution/blob/master/checkstyle-tester/diff.groovy#L251

Example: http://www.luolc.com/checkstyle-diff-report/issue3172/

**Comment by MEZk** [comment] 2017-03-22 19:10
@romani @rnveach 
Both README.md and summary index.html should have the warning message.

**Comment by romani** [comment] 2017-03-23 02:09
I am ok with warning on index-summary page.

**Comment by rnveach** [comment] 2017-03-25 18:22
Fix is merged.

> Both README.md and summary index.html should have the warning message.

Fix was for summary. @MEZk Do you plan to do readme too?

**Comment by MEZk** [comment] 2017-03-26 07:16
@rnveach 
Yes. I'll update README in separate commit.

**Comment by MEZk** [comment] 2017-03-26 17:23
@rnveach 
It turned out that the message had been already added.
```
In order to generate a compact diff report before and after your changes you can use diff.groovy script which performs all required work automatically. Note, diff.groovy ignores excludes specified in the list of projects file.
```

**Comment by romani** [comment] 2017-03-26 20:15
Let's close this issue

**Closed** 2017-03-26 21:10 UTC
