### ISSUE TITLE
diff report: wrap words, highlight target

### ISSUE THREAD

**Issue by romani** [checkstyle/contribution#422] opened 2019-12-14 22:51 UTC
right now 
long file names are not wrapped in Chrome (but works fine in FF)
![image](https://user-images.githubusercontent.com/812984/70855533-1dee6a80-1e81-11ea-8390-99110ad35640.png)
When you open certain link with defined target by anchor "#A11", it is hard to understand what actual line is it. 

should be:
![image](https://user-images.githubusercontent.com/812984/70855508-a91b3080-1e80-11ea-9c50-97796c0ee6f8.png)

**Comment by rnveach** [comment] 2019-12-15 02:01
Partial duplicate of https://github.com/checkstyle/contribution/issues/400 which already talks about adding text next to `#`.

**Comment by rnveach** [comment] 2019-12-15 04:16
fix was merged

**Closed by rnveach** 2019-12-15 04:16 UTC
